### ISSUE TITLE
explain the code?

### ISSUE THREAD

**Issue by m3m3-chan** [cclin3721/Gender-age-prediction-on-webcam#1]
Hello, 
Great work on this project!
Is it possible to explain briefly the difference between the 2 different age estimators that you use for age detection? 

thanks,

**Comment by cclin3721** [comment]
Hi Chan,
     To compare the difference between one open source and the API provided by Tencent, I make the program.  So you an see the difference on the screen. In my little experience Tencent is more accurate in the experiment.  XD

**Comment by m3m3-chan** [comment]
thanks !
